function startMRSmatlab_multicore
% function startMRSmatlab_multicore
% 
% Sets the MRSmatlab path & starts the matlab slave  
% ========================

addpath(...
   [pwd filesep 'extern'], ...
   [pwd filesep 'extern' filesep 'Factorize'], ...
   [pwd filesep 'extern' filesep 'GUILayout-v1p9'], ...
   [pwd filesep 'extern' filesep 'GUILayout-v1p9' filesep 'layoutHelp'], ...
   [pwd filesep 'extern' filesep 'GUILayout-v1p9' filesep 'Patch'], ...
   [pwd filesep 'extern' filesep 'exp2fit'], ...
   [pwd filesep 'extern' filesep 'pics'], ...
   [pwd filesep 'extern' filesep 'multicore'], ...
   [pwd filesep 'userinterfaces'], ...
   [pwd filesep 'userinterfaces' filesep 'icons'], ...
   [pwd filesep 'functions' filesep 'MRSSigPro'], ... 
   [pwd filesep 'functions' filesep 'FileConverter'], ... 
   [pwd filesep 'functions' filesep 'MRSKernel'], ...
   [pwd filesep 'functions' filesep 'MRSModelling'], ...
   [pwd filesep 'functions' filesep 'MRSInversionQT' filesep 'GA'], ...
   [pwd filesep 'functions' filesep 'MRSInversionQT'], ...
   [pwd filesep 'functions' filesep 'MRSInversionT1'], ...
   [pwd filesep 'functions' filesep 'CommonUsed']);

startmulticoreslave