
% Problem: dropdown menus in maingui can be changed... include uiwait in
% maingui?

function [fdata,proclog] = mrs_show_proclog(maingui,fdata,proclog,iQ,irec,irx,isig)
    
    % update gui status
    mrs_setguistatus(maingui,1,'Searching processing history...')

    % gui variables
    temp_fdata   = fdata;       % temp structures required for cancelling
    temp_proclog = proclog;
    
    % assemble table data
    type = {'  keep',...
            '  HNC',...
            '  despike',...
            '  local NC',...
            '  global NC',...
            '  calc global TF',...
            };
        
    id = find(...
        proclog.event(:,1) < 6 & ...        % exclude calc TF (6) & trim (101)
        proclog.event(:,2) == iQ & ...
        proclog.event(:,3) == irec & ...
        proclog.event(:,4) == irx & ...
        proclog.event(:,5) == isig); % find ids for this record
    
    
    clog = proclog.event(id,:);
    
    tabledata      = cell(size(id,1),3);
    %tabledata(:,1) = {true};
    
    for ilog = 1:size(clog,1)
        tabledata(ilog,1) = {id(ilog)}; 
        tabledata(ilog,2) = type(clog(ilog,1));
        tabledata(ilog,3) = {clog(ilog,7)};
    end    
    
    % allow only one instance of gui
    oldfigure = findobj('Name', 'Processing log for current FID');
    if ~isempty(oldfigure)
        delete(oldfigure)
    end
    
   
    % create gui figure
    gui.figureID = figure( ...
        'Name', 'Processing log for current FID', ...
        'NumberTitle', 'off', ...
        'MenuBar', 'none', ...
        'Toolbar', 'none', ...
        'HandleVisibility', 'on' );
    
    % gui figure size
    screensz = get(0,'ScreenSize');
    set(gui.figureID, 'Position', [15 screensz(4)-375 220 250])

    mainbox = uiextras.VBox('Parent', gui.figureID);

    % gui table
    box_h1 = uiextras.HBox('Parent', mainbox);    
    gui.table = uitable('Parent', box_h1);
    set(gui.table, ...
        'CellEditCallback', @onEditTable, ...
        'ColumnName', {'ID', 'type', 'Info'}, ...
        'ColumnWidth', {30 100 50}, ...
        'ColumnEditable', [false false false], ...
        'ColumnFormat', {'numeric','char','numeric'},...
        'Data', tabledata, ...
        'RowName', []);
    
    % gui pushbuttons
    box_h2 = uiextras.HBox('Parent', mainbox);
    gui.edit_status = uicontrol(...
        'Style', 'Text', ...
        'Parent', box_h2, ...
        'Enable', 'off', ...
        'String', ' ');
    gui.pushbutton_cancel = uicontrol(...
        'Enable', 'on', ...
        'Style', 'Pushbutton', ...
        'Parent', box_h2, ...
        'String', 'CLOSE', ...
        'Callback', @onClose);
    set(box_h2, 'Sizes', [-1 50])         
    
    set(mainbox, 'Sizes', [-1 30])
    
    function onClose(a,b)
        uiresume(gui.figureID)
        delete(gui.figureID)
    end 

uiwait(gui.figureID)
end
